server:
  port: 8092
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.78.129
  rabbitmq:
    host: 192.168.78.129
    port: 5672
    virtual-host: /
    username: zhx
    password: zhx
jwt:
  token:
    pubKeyPath: D:\MY_Codes\rsa\rsa.pub
    cookieName: gmall-token
    expireTime: 7776000
    userKey: user-key
alipay:
  app_id: 2016101800713393
  notify_url: http://5jgqzzlelb.52http.tech/api/order/pay/success # 域名是哲西云提供的域名，路径是订单支付成功回调的路径
  return_url: http://localhost:2000/pay/success.html
  sign_type: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do