server:
  port: 8089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
jwt:
  token:
    pubKeyPath: D:\My_Code\rsa\rsa.pub
    priKeyPath: D:\My_Code\rsa\rsa.pri
    secret: aslkdSSFDfsdfa@#$%@askhdf
    cookieName: gmall-token
    expireTime: 30
